name: Build .NET Framework App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    name: Build .NET Framework App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore "StudentManagementSystem.sln"

    - name: Build the solution
      run: msbuild "StudentManagementSystem.sln" /p:Configuration=Release /p:Platform="Any CPU"
